### ISSUE TITLE
unable to see user

### ISSUE THREAD

**Issue by ivandi1980** [ivandi1980/e-rapat#5]
Unable to load the requested file: user/index.php
@davedjoh

**Comment by davedjoh** [comment]
how it's look like?

**Comment by ivandi1980** [comment]
Unable to load the requested file: user/index.php means There's no view named index on user's folder so created it

**Comment by davedjoh** [comment]
on progress

**Comment by davedjoh** [comment]
Done!!
bug fixed unable to see user #5 by connecting all css & js to cdn
